GET http://localhost:3003/api/users HTTP/1.1

###
GET http://localhost:3003/api/users/616ec0137c78f9476cc773a8 HTTP/1.1
content-type: application/json

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "fullName": "yip4",
    "email": "yip4@mail.com",
    "password": "yip"
}

###
PUT http://localhost:3003/api/users/616e732a0c2d5b3a791f5467 HTTP/1.1
content-type: application/json

{
  "shared": 0
}